### PR TITLE
Improve formatting of Telemetry docs (part 2)

### PR DESCRIPTION
**Pull request by joshprice**
- Fix the other missing backtick I didn't spot in #185
- Remove colons and add newlines for consistency thoughout

### CODE REVIEW

**Comment by sneako** [comment]
Thank you! This time I checked out the PR and generated the docs :smile:  Can we get the "Measurements" and "Metadata" titles aligned at the same level of indentation?
telemetry-docs

**Comment by joshprice** [comment]
Weird, I didn't change those, so assuming it was already like that. Will take a look.

**Comment by joshprice** [comment]
OK not as many options here as I thought there might be. I don't think you can nest like that, although it's possibly an Earmark bug?

How do you feel about this as a workaround? I reckon taking the bullet off the event looks better, but your call.

Screen Shot 2022-04-25 at 7 45 31 pm

**Comment by joshprice** [comment]
Pushed up the fix, let me know if you want to do a diff way. Might be worth just double checking all the new h3 titles, just in case I missed something.

**Comment by sneako** [comment]
Looks good to me, thank you!

**Pull request merged**
