### PR TITLE
Fix calls to deprecated Logger.warn/2

### PR DESCRIPTION
**Pull request by solar05**
I'm not sure if this is the right way. Maybe it's also possible to bump the minimum Elixir version to 1.11? But I guess that would be a breaking change :/

### CODE REVIEW

**Comment by wojtekmach** [comment]
+1 for requiring Elixir 1.11.

**Comment by wojtekmach** [comment]
If we merge this as is, we should update Elixir requirement in mix.exs.

**Comment by solar05** [comment]
Done, also bump elixir CI version 👌

**Comment by sneako** [comment]
Thank you!

**Pull request merged**
