### PR TITLE
Use Mint.HTTP1 in HTTP1 conn

### PR DESCRIPTION
**Pull request by whatyouhide**
See https://github.com/sneako/finch/issues/265#issuecomment-1954896743.

### CODE REVIEW

**Comment by sneako** [comment]
Hey @whatyouhide !  Thanks for the PR. I guess we should also remove this part of the docs: https://github.com/sneako/finch/pull/250/files#diff-bfab6b899762596b9df3f3d7e719f23d973285f555d89dd956cfd59e652a7a25R60-R61

@wojtekmach want to make sure you see this, did you have any ideas for a workaround in Req?

**Comment by wojtekmach** [comment]
Wait are we basically reverting https://github.com/sneako/finch/pull/250 or I'm missing something? It's fine if that is the plan i.e. we can't make it work but want to make sure.

**Comment by sneako** [comment]
Yeah that is what would happen if we merge this PR... I do think Req should be able to support arbitrary protocols for unknown hosts, so I'm not sure if we should proceed this way. 

I guess the only alternative we have thought of so far is to "port HTTP/2 flow control in HTTP/1 connections" as @wojtekmach mentioned in the linked comment?

**Comment by whatyouhide** [comment]
Okay, let's close this and figure out a good solution in #265 first.

**Pull request closed without merging**
